### ISSUE TITLE
Dash character (-) ignored in s_header_field state

### ISSUE THREAD

**Issue by DmitriyMaksimov** [iafonov/multipart-parser-c#12]
multipart_parser.c has following condition in s_header_field state:

        if (c == '-') {
          break;
        }

But '-' is valid character for header's name, for example when you upload a file you'll find these fields:

    Content-Disposition: form-data; name="upload"; filename="a.data"
    Content-Type: application/octet-stream

Moreover if you remove above if statement following code:

        cl = tolower(c);
        if (cl < 'a' || cl > 'z') {
          multipart_log("invalid character in header name");
          return i;
        }

will log "invalid character in header name" error and return.

**Comment by vincentbernat** [comment]
This bug seems to be fixed in #19.

**Comment by DmitriyMaksimov** [comment]
@vincentbernat - the fix looks good
